name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 1 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 9e87617937a411f00673452dc187f71a
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
